version: "2"
run:
  build-tags:
    - local
    - awss3
    - minio
    - gcpstorage
    - azureblob
    - glacier
    - azurearchive
  tests: false
linters:
  enable:
    - err113
    - goconst
    - gosec
    - misspell
    - unconvert
  disable:
    - gocritic
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - appendAssign
        - hugeParam
        - ifElseChain
      enabled-tags:
        - diagnostic
        - performance
    govet:
      enable:
        - shadow
    lll:
      line-length: 120
      tab-width: 1
    misspell:
      locale: US
    staticcheck:
      checks:
        - -SA1019
        - -SA4005
        - SA*
        - ST*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
          - errcheck
          - goconst
          - gocritic
          - gosec
          - ineffassign
          - staticcheck
          - unused
        path: _test\.go$
      - linters:
          - unused
        path: test_errors\.go$
      - linters:
          - unused
        path: test_helpers\.go$
      - linters:
          - unused
        path: mock_.*\.go$
      - linters:
          - err113
          - errcheck
          - gosec
        path: test/integration
      - linters:
          - err113
          - errcheck
          - gocritic
        path: cmd/
      - linters:
          - err113
          - errcheck
          - gocritic
        path: examples/
      - linters:
          - errcheck
        path: test/
        text: Error return value of .* is not checked
      - linters:
          - gosec
        text: G104
      - linters:
          - err113
        path: _test\.go$
        text: do not define dynamic errors
      - linters:
          - staticcheck
        text: 'SA1012: do not pass a nil Context'
      - linters:
          - gocritic
        text: ifElseChain
      - linters:
          - unused
        text: is unused
      - linters:
          - unused
        text: func.*is unused
      - linters:
          - unused
        text: type.*is unused
      - linters:
          - unused
        text: var.*is unused
      - linters:
          - staticcheck
        text: 'QF1003:'
      - linters:
          - staticcheck
        text: 'QF1008:'
      - linters:
          - govet
        text: shadow
      - linters:
          - gocritic
        text: exitAfterDefer
      - linters:
          - gocritic
        text: octalLiteral
      - linters:
          - gocritic
        text: emptyStringTest
      - linters:
          - gocritic
        text: paramTypeCombine
      - linters:
          - gocritic
        text: unnecessaryBlock
      - linters:
          - gocritic
        text: commentedOutCode
      - linters:
          - gocritic
        text: builtinShadow
      - linters:
          - gocritic
        text: preferStringWriter
      - linters:
          - staticcheck
        text: S1009
      - linters:
          - ineffassign
        text: ineffectual assignment
      - linters:
          - unused
        path: _test\.go$
        text: unused
      - linters:
          - unused
        path: _test\.go$
        text: is unused
      - linters:
          - goconst
        path: _test\.go$
        text: make it a constant
      - linters:
          - staticcheck
        text: SA1019.*deprecated
      - linters:
          - goconst
        text: has 3 occurrences
      - linters:
          - goconst
        text: has 4 occurrences
      - linters:
          - errcheck
        path: pkg/(local|audit|memory)/
        text: Error return value of.*is not checked
      - linters:
          - misspell
        text: '`cancelled` is a misspelling of `canceled`'
      - linters:
          - err113
        text: context\.(Canceled|DeadlineExceeded)
      - linters:
          - err113
        text: http\.ErrServerClosed
      - linters:
          - err113
        text: common\.ErrPolicyNotFound
      - linters:
          - staticcheck
        text: 'QF1008:'
      - linters:
          - staticcheck
        text: 'QF1003:'
      - linters:
          - staticcheck
        text: 'S1009:'
      - linters:
          - staticcheck
        text: 'ST1011:'
      - linters:
          - gocritic
        text: 'ifElseChain:'
      - linters:
          - errcheck
          - gocritic
          - staticcheck
          - unconvert
        path: pkg/(server|storagefs|replication)/
      - linters:
          - staticcheck
          - unused
        path: pkg/(s3|minio)/
      - linters:
          - gocritic
          - staticcheck
        path: pkg/azure/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - github.com/jeremyhahn/go-objstore
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - cmd/
