run:
  timeout: 5m
  tests: true
  build-tags:
    - local
    - awss3
    - gcpstorage
    - azureblob
    - glacier

linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  goimports:
    local-prefixes: github.com/jeremyhahn/go-objstore
  govet:
    enable:
      - shadow
  errcheck:
    check-type-assertions: true
    check-blank: true
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - appendAssign
      - hugeParam
  staticcheck:
    checks:
      - all
      - '-SA4005'
  goconst:
    min-len: 3
    min-occurrences: 3
  lll:
    line-length: 120
    tab-width: 1

linters:
  enable:
    - errcheck
    - gocritic
    - govet
    - gosec
    - goconst
    - err113
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
  fast: false

issues:
  exclude-rules:
    - path: '_test\.go$'
      linters:
        - errcheck
        - gosec
        - gocritic
        - err113
        - goconst
        - staticcheck
    - path: 'test/integration'
      linters:
        - errcheck
        - gosec
        - err113
    - path: 'cmd/objstorelib'
      linters:
        - errcheck
        - err113
        - gocritic
        - gofmt
    - path: 'examples/'
      linters:
        - errcheck
        - err113
    - text: 'Error return value of .* is not checked'
      linters:
        - errcheck
      path: 'test/'
    - text: 'G104'
      linters:
        - gosec
    - text: 'do not define dynamic errors'
      linters:
        - err113
    - text: 'SA1012: do not pass a nil Context'
      linters:
        - staticcheck
    - text: 'ifElseChain'
      linters:
        - gocritic
    - text: 'shadow'
      linters:
        - govet
    - text: 'exitAfterDefer'
      linters:
        - gocritic
    - text: 'octalLiteral'
      linters:
        - gocritic
    - text: 'emptyStringTest'
      linters:
        - gocritic
    - text: 'paramTypeCombine'
      linters:
        - gocritic
    - text: 'unnecessaryBlock'
      linters:
        - gocritic
    - text: 'commentedOutCode'
      linters:
        - gocritic
    - text: 'builtinShadow'
      linters:
        - gocritic
    - text: 'preferStringWriter'
      linters:
        - gocritic
    - text: 'S1009'
      linters:
        - gosimple
    - text: 'ineffectual assignment'
      linters:
        - ineffassign
    - text: 'unused'
      linters:
        - unused
      path: '_test\.go$'
    - text: 'SA1019.*deprecated'
      linters:
        - staticcheck
    - text: 'has 3 occurrences'
      linters:
        - goconst
    - text: 'has 4 occurrences'
      linters:
        - goconst
    - text: 'Error return value of.*is not checked'
      linters:
        - errcheck
      path: 'pkg/(local|audit)/'
    - text: '`cancelled` is a misspelling of `canceled`'
      linters:
        - misspell
    - text: 'context\.(Canceled|DeadlineExceeded)'
      linters:
        - err113
    - text: 'http\.ErrServerClosed'
      linters:
        - err113
    - text: 'common\.ErrPolicyNotFound'
      linters:
        - err113
    - path: 'pkg/(server|storagefs|replication)/'
      linters:
        - errcheck
        - gocritic
        - staticcheck
        - unconvert
    - path: 'pkg/s3/'
      linters:
        - unused

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
