// Copyright (c) 2025 Jeremy Hahn
// Copyright (c) 2025 Automate The Things, LLC
//
// This file is part of go-objstore.
//
// go-objstore is dual-licensed:
//
// 1. GNU Affero General Public License v3.0 (AGPL-3.0)
//    See LICENSE file or visit https://www.gnu.org/licenses/agpl-3.0.html
//
// 2. Commercial License
//    Contact licensing@automatethethings.com for commercial licensing options.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: objstore.proto

package objstorepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObjectStore_Put_FullMethodName                     = "/objstore.v1.ObjectStore/Put"
	ObjectStore_Get_FullMethodName                     = "/objstore.v1.ObjectStore/Get"
	ObjectStore_Delete_FullMethodName                  = "/objstore.v1.ObjectStore/Delete"
	ObjectStore_List_FullMethodName                    = "/objstore.v1.ObjectStore/List"
	ObjectStore_Exists_FullMethodName                  = "/objstore.v1.ObjectStore/Exists"
	ObjectStore_GetMetadata_FullMethodName             = "/objstore.v1.ObjectStore/GetMetadata"
	ObjectStore_UpdateMetadata_FullMethodName          = "/objstore.v1.ObjectStore/UpdateMetadata"
	ObjectStore_Health_FullMethodName                  = "/objstore.v1.ObjectStore/Health"
	ObjectStore_Archive_FullMethodName                 = "/objstore.v1.ObjectStore/Archive"
	ObjectStore_AddPolicy_FullMethodName               = "/objstore.v1.ObjectStore/AddPolicy"
	ObjectStore_RemovePolicy_FullMethodName            = "/objstore.v1.ObjectStore/RemovePolicy"
	ObjectStore_GetPolicies_FullMethodName             = "/objstore.v1.ObjectStore/GetPolicies"
	ObjectStore_ApplyPolicies_FullMethodName           = "/objstore.v1.ObjectStore/ApplyPolicies"
	ObjectStore_AddReplicationPolicy_FullMethodName    = "/objstore.v1.ObjectStore/AddReplicationPolicy"
	ObjectStore_RemoveReplicationPolicy_FullMethodName = "/objstore.v1.ObjectStore/RemoveReplicationPolicy"
	ObjectStore_GetReplicationPolicies_FullMethodName  = "/objstore.v1.ObjectStore/GetReplicationPolicies"
	ObjectStore_GetReplicationPolicy_FullMethodName    = "/objstore.v1.ObjectStore/GetReplicationPolicy"
	ObjectStore_TriggerReplication_FullMethodName      = "/objstore.v1.ObjectStore/TriggerReplication"
	ObjectStore_GetReplicationStatus_FullMethodName    = "/objstore.v1.ObjectStore/GetReplicationStatus"
)

// ObjectStoreClient is the client API for ObjectStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ObjectStore service provides a unified interface for object storage operations.
type ObjectStoreClient interface {
	// Put stores an object in the backend.
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// Get retrieves an object from the backend with streaming support for large files.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error)
	// Delete removes an object from the backend.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// List returns a list of objects that match the given criteria.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Exists checks if an object exists in the backend.
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error)
	// GetMetadata retrieves only the metadata for an object without its content.
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
	// UpdateMetadata updates the metadata for an existing object.
	UpdateMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*UpdateMetadataResponse, error)
	// Health check endpoint for service health monitoring.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Archive copies an object to an archival storage backend.
	Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error)
	// AddPolicy adds a new lifecycle policy.
	AddPolicy(ctx context.Context, in *AddPolicyRequest, opts ...grpc.CallOption) (*AddPolicyResponse, error)
	// RemovePolicy removes an existing lifecycle policy.
	RemovePolicy(ctx context.Context, in *RemovePolicyRequest, opts ...grpc.CallOption) (*RemovePolicyResponse, error)
	// GetPolicies retrieves all lifecycle policies.
	GetPolicies(ctx context.Context, in *GetPoliciesRequest, opts ...grpc.CallOption) (*GetPoliciesResponse, error)
	// ApplyPolicies executes all lifecycle policies.
	ApplyPolicies(ctx context.Context, in *ApplyPoliciesRequest, opts ...grpc.CallOption) (*ApplyPoliciesResponse, error)
	// AddReplicationPolicy adds a new replication policy.
	AddReplicationPolicy(ctx context.Context, in *AddReplicationPolicyRequest, opts ...grpc.CallOption) (*AddReplicationPolicyResponse, error)
	// RemoveReplicationPolicy removes an existing replication policy.
	RemoveReplicationPolicy(ctx context.Context, in *RemoveReplicationPolicyRequest, opts ...grpc.CallOption) (*RemoveReplicationPolicyResponse, error)
	// GetReplicationPolicies retrieves all replication policies.
	GetReplicationPolicies(ctx context.Context, in *GetReplicationPoliciesRequest, opts ...grpc.CallOption) (*GetReplicationPoliciesResponse, error)
	// GetReplicationPolicy retrieves a specific replication policy.
	GetReplicationPolicy(ctx context.Context, in *GetReplicationPolicyRequest, opts ...grpc.CallOption) (*GetReplicationPolicyResponse, error)
	// TriggerReplication triggers synchronization for one or all policies.
	TriggerReplication(ctx context.Context, in *TriggerReplicationRequest, opts ...grpc.CallOption) (*TriggerReplicationResponse, error)
	// GetReplicationStatus retrieves status and metrics for a specific replication policy.
	GetReplicationStatus(ctx context.Context, in *GetReplicationStatusRequest, opts ...grpc.CallOption) (*GetReplicationStatusResponse, error)
}

type objectStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectStoreClient(cc grpc.ClientConnInterface) ObjectStoreClient {
	return &objectStoreClient{cc}
}

func (c *objectStoreClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, ObjectStore_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObjectStore_ServiceDesc.Streams[0], ObjectStore_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObjectStore_GetClient = grpc.ServerStreamingClient[GetResponse]

func (c *objectStoreClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ObjectStore_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ObjectStore_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, ObjectStore_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, ObjectStore_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) UpdateMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*UpdateMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMetadataResponse)
	err := c.cc.Invoke(ctx, ObjectStore_UpdateMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ObjectStore_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveResponse)
	err := c.cc.Invoke(ctx, ObjectStore_Archive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) AddPolicy(ctx context.Context, in *AddPolicyRequest, opts ...grpc.CallOption) (*AddPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPolicyResponse)
	err := c.cc.Invoke(ctx, ObjectStore_AddPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) RemovePolicy(ctx context.Context, in *RemovePolicyRequest, opts ...grpc.CallOption) (*RemovePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePolicyResponse)
	err := c.cc.Invoke(ctx, ObjectStore_RemovePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) GetPolicies(ctx context.Context, in *GetPoliciesRequest, opts ...grpc.CallOption) (*GetPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoliciesResponse)
	err := c.cc.Invoke(ctx, ObjectStore_GetPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) ApplyPolicies(ctx context.Context, in *ApplyPoliciesRequest, opts ...grpc.CallOption) (*ApplyPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyPoliciesResponse)
	err := c.cc.Invoke(ctx, ObjectStore_ApplyPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) AddReplicationPolicy(ctx context.Context, in *AddReplicationPolicyRequest, opts ...grpc.CallOption) (*AddReplicationPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddReplicationPolicyResponse)
	err := c.cc.Invoke(ctx, ObjectStore_AddReplicationPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) RemoveReplicationPolicy(ctx context.Context, in *RemoveReplicationPolicyRequest, opts ...grpc.CallOption) (*RemoveReplicationPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveReplicationPolicyResponse)
	err := c.cc.Invoke(ctx, ObjectStore_RemoveReplicationPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) GetReplicationPolicies(ctx context.Context, in *GetReplicationPoliciesRequest, opts ...grpc.CallOption) (*GetReplicationPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReplicationPoliciesResponse)
	err := c.cc.Invoke(ctx, ObjectStore_GetReplicationPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) GetReplicationPolicy(ctx context.Context, in *GetReplicationPolicyRequest, opts ...grpc.CallOption) (*GetReplicationPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReplicationPolicyResponse)
	err := c.cc.Invoke(ctx, ObjectStore_GetReplicationPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) TriggerReplication(ctx context.Context, in *TriggerReplicationRequest, opts ...grpc.CallOption) (*TriggerReplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerReplicationResponse)
	err := c.cc.Invoke(ctx, ObjectStore_TriggerReplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) GetReplicationStatus(ctx context.Context, in *GetReplicationStatusRequest, opts ...grpc.CallOption) (*GetReplicationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReplicationStatusResponse)
	err := c.cc.Invoke(ctx, ObjectStore_GetReplicationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectStoreServer is the server API for ObjectStore service.
// All implementations must embed UnimplementedObjectStoreServer
// for forward compatibility.
//
// ObjectStore service provides a unified interface for object storage operations.
type ObjectStoreServer interface {
	// Put stores an object in the backend.
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// Get retrieves an object from the backend with streaming support for large files.
	Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error
	// Delete removes an object from the backend.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// List returns a list of objects that match the given criteria.
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Exists checks if an object exists in the backend.
	Exists(context.Context, *ExistsRequest) (*ExistsResponse, error)
	// GetMetadata retrieves only the metadata for an object without its content.
	GetMetadata(context.Context, *GetMetadataRequest) (*MetadataResponse, error)
	// UpdateMetadata updates the metadata for an existing object.
	UpdateMetadata(context.Context, *UpdateMetadataRequest) (*UpdateMetadataResponse, error)
	// Health check endpoint for service health monitoring.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Archive copies an object to an archival storage backend.
	Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error)
	// AddPolicy adds a new lifecycle policy.
	AddPolicy(context.Context, *AddPolicyRequest) (*AddPolicyResponse, error)
	// RemovePolicy removes an existing lifecycle policy.
	RemovePolicy(context.Context, *RemovePolicyRequest) (*RemovePolicyResponse, error)
	// GetPolicies retrieves all lifecycle policies.
	GetPolicies(context.Context, *GetPoliciesRequest) (*GetPoliciesResponse, error)
	// ApplyPolicies executes all lifecycle policies.
	ApplyPolicies(context.Context, *ApplyPoliciesRequest) (*ApplyPoliciesResponse, error)
	// AddReplicationPolicy adds a new replication policy.
	AddReplicationPolicy(context.Context, *AddReplicationPolicyRequest) (*AddReplicationPolicyResponse, error)
	// RemoveReplicationPolicy removes an existing replication policy.
	RemoveReplicationPolicy(context.Context, *RemoveReplicationPolicyRequest) (*RemoveReplicationPolicyResponse, error)
	// GetReplicationPolicies retrieves all replication policies.
	GetReplicationPolicies(context.Context, *GetReplicationPoliciesRequest) (*GetReplicationPoliciesResponse, error)
	// GetReplicationPolicy retrieves a specific replication policy.
	GetReplicationPolicy(context.Context, *GetReplicationPolicyRequest) (*GetReplicationPolicyResponse, error)
	// TriggerReplication triggers synchronization for one or all policies.
	TriggerReplication(context.Context, *TriggerReplicationRequest) (*TriggerReplicationResponse, error)
	// GetReplicationStatus retrieves status and metrics for a specific replication policy.
	GetReplicationStatus(context.Context, *GetReplicationStatusRequest) (*GetReplicationStatusResponse, error)
	mustEmbedUnimplementedObjectStoreServer()
}

// UnimplementedObjectStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObjectStoreServer struct{}

func (UnimplementedObjectStoreServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedObjectStoreServer) Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedObjectStoreServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedObjectStoreServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedObjectStoreServer) Exists(context.Context, *ExistsRequest) (*ExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedObjectStoreServer) GetMetadata(context.Context, *GetMetadataRequest) (*MetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedObjectStoreServer) UpdateMetadata(context.Context, *UpdateMetadataRequest) (*UpdateMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetadata not implemented")
}
func (UnimplementedObjectStoreServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedObjectStoreServer) Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Archive not implemented")
}
func (UnimplementedObjectStoreServer) AddPolicy(context.Context, *AddPolicyRequest) (*AddPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPolicy not implemented")
}
func (UnimplementedObjectStoreServer) RemovePolicy(context.Context, *RemovePolicyRequest) (*RemovePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePolicy not implemented")
}
func (UnimplementedObjectStoreServer) GetPolicies(context.Context, *GetPoliciesRequest) (*GetPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicies not implemented")
}
func (UnimplementedObjectStoreServer) ApplyPolicies(context.Context, *ApplyPoliciesRequest) (*ApplyPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPolicies not implemented")
}
func (UnimplementedObjectStoreServer) AddReplicationPolicy(context.Context, *AddReplicationPolicyRequest) (*AddReplicationPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReplicationPolicy not implemented")
}
func (UnimplementedObjectStoreServer) RemoveReplicationPolicy(context.Context, *RemoveReplicationPolicyRequest) (*RemoveReplicationPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveReplicationPolicy not implemented")
}
func (UnimplementedObjectStoreServer) GetReplicationPolicies(context.Context, *GetReplicationPoliciesRequest) (*GetReplicationPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplicationPolicies not implemented")
}
func (UnimplementedObjectStoreServer) GetReplicationPolicy(context.Context, *GetReplicationPolicyRequest) (*GetReplicationPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplicationPolicy not implemented")
}
func (UnimplementedObjectStoreServer) TriggerReplication(context.Context, *TriggerReplicationRequest) (*TriggerReplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerReplication not implemented")
}
func (UnimplementedObjectStoreServer) GetReplicationStatus(context.Context, *GetReplicationStatusRequest) (*GetReplicationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplicationStatus not implemented")
}
func (UnimplementedObjectStoreServer) mustEmbedUnimplementedObjectStoreServer() {}
func (UnimplementedObjectStoreServer) testEmbeddedByValue()                     {}

// UnsafeObjectStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectStoreServer will
// result in compilation errors.
type UnsafeObjectStoreServer interface {
	mustEmbedUnimplementedObjectStoreServer()
}

func RegisterObjectStoreServer(s grpc.ServiceRegistrar, srv ObjectStoreServer) {
	// If the following call pancis, it indicates UnimplementedObjectStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObjectStore_ServiceDesc, srv)
}

func _ObjectStore_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObjectStoreServer).Get(m, &grpc.GenericServerStream[GetRequest, GetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObjectStore_GetServer = grpc.ServerStreamingServer[GetResponse]

func _ObjectStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_UpdateMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).UpdateMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_UpdateMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).UpdateMetadata(ctx, req.(*UpdateMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Archive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Archive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Archive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Archive(ctx, req.(*ArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_AddPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).AddPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_AddPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).AddPolicy(ctx, req.(*AddPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_RemovePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).RemovePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_RemovePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).RemovePolicy(ctx, req.(*RemovePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_GetPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).GetPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_GetPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).GetPolicies(ctx, req.(*GetPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_ApplyPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).ApplyPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_ApplyPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).ApplyPolicies(ctx, req.(*ApplyPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_AddReplicationPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReplicationPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).AddReplicationPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_AddReplicationPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).AddReplicationPolicy(ctx, req.(*AddReplicationPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_RemoveReplicationPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReplicationPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).RemoveReplicationPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_RemoveReplicationPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).RemoveReplicationPolicy(ctx, req.(*RemoveReplicationPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_GetReplicationPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplicationPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).GetReplicationPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_GetReplicationPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).GetReplicationPolicies(ctx, req.(*GetReplicationPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_GetReplicationPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplicationPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).GetReplicationPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_GetReplicationPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).GetReplicationPolicy(ctx, req.(*GetReplicationPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_TriggerReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).TriggerReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_TriggerReplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).TriggerReplication(ctx, req.(*TriggerReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_GetReplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).GetReplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_GetReplicationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).GetReplicationStatus(ctx, req.(*GetReplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectStore_ServiceDesc is the grpc.ServiceDesc for ObjectStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "objstore.v1.ObjectStore",
	HandlerType: (*ObjectStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _ObjectStore_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ObjectStore_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ObjectStore_List_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _ObjectStore_Exists_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _ObjectStore_GetMetadata_Handler,
		},
		{
			MethodName: "UpdateMetadata",
			Handler:    _ObjectStore_UpdateMetadata_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ObjectStore_Health_Handler,
		},
		{
			MethodName: "Archive",
			Handler:    _ObjectStore_Archive_Handler,
		},
		{
			MethodName: "AddPolicy",
			Handler:    _ObjectStore_AddPolicy_Handler,
		},
		{
			MethodName: "RemovePolicy",
			Handler:    _ObjectStore_RemovePolicy_Handler,
		},
		{
			MethodName: "GetPolicies",
			Handler:    _ObjectStore_GetPolicies_Handler,
		},
		{
			MethodName: "ApplyPolicies",
			Handler:    _ObjectStore_ApplyPolicies_Handler,
		},
		{
			MethodName: "AddReplicationPolicy",
			Handler:    _ObjectStore_AddReplicationPolicy_Handler,
		},
		{
			MethodName: "RemoveReplicationPolicy",
			Handler:    _ObjectStore_RemoveReplicationPolicy_Handler,
		},
		{
			MethodName: "GetReplicationPolicies",
			Handler:    _ObjectStore_GetReplicationPolicies_Handler,
		},
		{
			MethodName: "GetReplicationPolicy",
			Handler:    _ObjectStore_GetReplicationPolicy_Handler,
		},
		{
			MethodName: "TriggerReplication",
			Handler:    _ObjectStore_TriggerReplication_Handler,
		},
		{
			MethodName: "GetReplicationStatus",
			Handler:    _ObjectStore_GetReplicationStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _ObjectStore_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "objstore.proto",
}
