# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import objstore_pb2 as objstore__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in objstore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectStoreStub(object):
    """ObjectStore service provides a unified interface for object storage operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/objstore.v1.ObjectStore/Put',
                request_serializer=objstore__pb2.PutRequest.SerializeToString,
                response_deserializer=objstore__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_stream(
                '/objstore.v1.ObjectStore/Get',
                request_serializer=objstore__pb2.GetRequest.SerializeToString,
                response_deserializer=objstore__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/objstore.v1.ObjectStore/Delete',
                request_serializer=objstore__pb2.DeleteRequest.SerializeToString,
                response_deserializer=objstore__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/objstore.v1.ObjectStore/List',
                request_serializer=objstore__pb2.ListRequest.SerializeToString,
                response_deserializer=objstore__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Exists = channel.unary_unary(
                '/objstore.v1.ObjectStore/Exists',
                request_serializer=objstore__pb2.ExistsRequest.SerializeToString,
                response_deserializer=objstore__pb2.ExistsResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/objstore.v1.ObjectStore/GetMetadata',
                request_serializer=objstore__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=objstore__pb2.MetadataResponse.FromString,
                _registered_method=True)
        self.UpdateMetadata = channel.unary_unary(
                '/objstore.v1.ObjectStore/UpdateMetadata',
                request_serializer=objstore__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=objstore__pb2.UpdateMetadataResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/objstore.v1.ObjectStore/Health',
                request_serializer=objstore__pb2.HealthRequest.SerializeToString,
                response_deserializer=objstore__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Archive = channel.unary_unary(
                '/objstore.v1.ObjectStore/Archive',
                request_serializer=objstore__pb2.ArchiveRequest.SerializeToString,
                response_deserializer=objstore__pb2.ArchiveResponse.FromString,
                _registered_method=True)
        self.AddPolicy = channel.unary_unary(
                '/objstore.v1.ObjectStore/AddPolicy',
                request_serializer=objstore__pb2.AddPolicyRequest.SerializeToString,
                response_deserializer=objstore__pb2.AddPolicyResponse.FromString,
                _registered_method=True)
        self.RemovePolicy = channel.unary_unary(
                '/objstore.v1.ObjectStore/RemovePolicy',
                request_serializer=objstore__pb2.RemovePolicyRequest.SerializeToString,
                response_deserializer=objstore__pb2.RemovePolicyResponse.FromString,
                _registered_method=True)
        self.GetPolicies = channel.unary_unary(
                '/objstore.v1.ObjectStore/GetPolicies',
                request_serializer=objstore__pb2.GetPoliciesRequest.SerializeToString,
                response_deserializer=objstore__pb2.GetPoliciesResponse.FromString,
                _registered_method=True)
        self.ApplyPolicies = channel.unary_unary(
                '/objstore.v1.ObjectStore/ApplyPolicies',
                request_serializer=objstore__pb2.ApplyPoliciesRequest.SerializeToString,
                response_deserializer=objstore__pb2.ApplyPoliciesResponse.FromString,
                _registered_method=True)
        self.AddReplicationPolicy = channel.unary_unary(
                '/objstore.v1.ObjectStore/AddReplicationPolicy',
                request_serializer=objstore__pb2.AddReplicationPolicyRequest.SerializeToString,
                response_deserializer=objstore__pb2.AddReplicationPolicyResponse.FromString,
                _registered_method=True)
        self.RemoveReplicationPolicy = channel.unary_unary(
                '/objstore.v1.ObjectStore/RemoveReplicationPolicy',
                request_serializer=objstore__pb2.RemoveReplicationPolicyRequest.SerializeToString,
                response_deserializer=objstore__pb2.RemoveReplicationPolicyResponse.FromString,
                _registered_method=True)
        self.GetReplicationPolicies = channel.unary_unary(
                '/objstore.v1.ObjectStore/GetReplicationPolicies',
                request_serializer=objstore__pb2.GetReplicationPoliciesRequest.SerializeToString,
                response_deserializer=objstore__pb2.GetReplicationPoliciesResponse.FromString,
                _registered_method=True)
        self.GetReplicationPolicy = channel.unary_unary(
                '/objstore.v1.ObjectStore/GetReplicationPolicy',
                request_serializer=objstore__pb2.GetReplicationPolicyRequest.SerializeToString,
                response_deserializer=objstore__pb2.GetReplicationPolicyResponse.FromString,
                _registered_method=True)
        self.TriggerReplication = channel.unary_unary(
                '/objstore.v1.ObjectStore/TriggerReplication',
                request_serializer=objstore__pb2.TriggerReplicationRequest.SerializeToString,
                response_deserializer=objstore__pb2.TriggerReplicationResponse.FromString,
                _registered_method=True)
        self.GetReplicationStatus = channel.unary_unary(
                '/objstore.v1.ObjectStore/GetReplicationStatus',
                request_serializer=objstore__pb2.GetReplicationStatusRequest.SerializeToString,
                response_deserializer=objstore__pb2.GetReplicationStatusResponse.FromString,
                _registered_method=True)


class ObjectStoreServicer(object):
    """ObjectStore service provides a unified interface for object storage operations.
    """

    def Put(self, request, context):
        """Put stores an object in the backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Get retrieves an object from the backend with streaming support for large files.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete removes an object from the backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List returns a list of objects that match the given criteria.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Exists checks if an object exists in the backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """GetMetadata retrieves only the metadata for an object without its content.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMetadata(self, request, context):
        """UpdateMetadata updates the metadata for an existing object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check endpoint for service health monitoring.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Archive(self, request, context):
        """Archive copies an object to an archival storage backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPolicy(self, request, context):
        """AddPolicy adds a new lifecycle policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePolicy(self, request, context):
        """RemovePolicy removes an existing lifecycle policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicies(self, request, context):
        """GetPolicies retrieves all lifecycle policies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyPolicies(self, request, context):
        """ApplyPolicies executes all lifecycle policies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddReplicationPolicy(self, request, context):
        """Replication methods

        AddReplicationPolicy adds a new replication policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveReplicationPolicy(self, request, context):
        """RemoveReplicationPolicy removes an existing replication policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplicationPolicies(self, request, context):
        """GetReplicationPolicies retrieves all replication policies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplicationPolicy(self, request, context):
        """GetReplicationPolicy retrieves a specific replication policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerReplication(self, request, context):
        """TriggerReplication triggers synchronization for one or all policies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplicationStatus(self, request, context):
        """GetReplicationStatus retrieves status and metrics for a specific replication policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=objstore__pb2.PutRequest.FromString,
                    response_serializer=objstore__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_stream_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=objstore__pb2.GetRequest.FromString,
                    response_serializer=objstore__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=objstore__pb2.DeleteRequest.FromString,
                    response_serializer=objstore__pb2.DeleteResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=objstore__pb2.ListRequest.FromString,
                    response_serializer=objstore__pb2.ListResponse.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=objstore__pb2.ExistsRequest.FromString,
                    response_serializer=objstore__pb2.ExistsResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=objstore__pb2.GetMetadataRequest.FromString,
                    response_serializer=objstore__pb2.MetadataResponse.SerializeToString,
            ),
            'UpdateMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMetadata,
                    request_deserializer=objstore__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=objstore__pb2.UpdateMetadataResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=objstore__pb2.HealthRequest.FromString,
                    response_serializer=objstore__pb2.HealthResponse.SerializeToString,
            ),
            'Archive': grpc.unary_unary_rpc_method_handler(
                    servicer.Archive,
                    request_deserializer=objstore__pb2.ArchiveRequest.FromString,
                    response_serializer=objstore__pb2.ArchiveResponse.SerializeToString,
            ),
            'AddPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPolicy,
                    request_deserializer=objstore__pb2.AddPolicyRequest.FromString,
                    response_serializer=objstore__pb2.AddPolicyResponse.SerializeToString,
            ),
            'RemovePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePolicy,
                    request_deserializer=objstore__pb2.RemovePolicyRequest.FromString,
                    response_serializer=objstore__pb2.RemovePolicyResponse.SerializeToString,
            ),
            'GetPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicies,
                    request_deserializer=objstore__pb2.GetPoliciesRequest.FromString,
                    response_serializer=objstore__pb2.GetPoliciesResponse.SerializeToString,
            ),
            'ApplyPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyPolicies,
                    request_deserializer=objstore__pb2.ApplyPoliciesRequest.FromString,
                    response_serializer=objstore__pb2.ApplyPoliciesResponse.SerializeToString,
            ),
            'AddReplicationPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReplicationPolicy,
                    request_deserializer=objstore__pb2.AddReplicationPolicyRequest.FromString,
                    response_serializer=objstore__pb2.AddReplicationPolicyResponse.SerializeToString,
            ),
            'RemoveReplicationPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveReplicationPolicy,
                    request_deserializer=objstore__pb2.RemoveReplicationPolicyRequest.FromString,
                    response_serializer=objstore__pb2.RemoveReplicationPolicyResponse.SerializeToString,
            ),
            'GetReplicationPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicationPolicies,
                    request_deserializer=objstore__pb2.GetReplicationPoliciesRequest.FromString,
                    response_serializer=objstore__pb2.GetReplicationPoliciesResponse.SerializeToString,
            ),
            'GetReplicationPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicationPolicy,
                    request_deserializer=objstore__pb2.GetReplicationPolicyRequest.FromString,
                    response_serializer=objstore__pb2.GetReplicationPolicyResponse.SerializeToString,
            ),
            'TriggerReplication': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerReplication,
                    request_deserializer=objstore__pb2.TriggerReplicationRequest.FromString,
                    response_serializer=objstore__pb2.TriggerReplicationResponse.SerializeToString,
            ),
            'GetReplicationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicationStatus,
                    request_deserializer=objstore__pb2.GetReplicationStatusRequest.FromString,
                    response_serializer=objstore__pb2.GetReplicationStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'objstore.v1.ObjectStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('objstore.v1.ObjectStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectStore(object):
    """ObjectStore service provides a unified interface for object storage operations.
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/Put',
            objstore__pb2.PutRequest.SerializeToString,
            objstore__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/objstore.v1.ObjectStore/Get',
            objstore__pb2.GetRequest.SerializeToString,
            objstore__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/Delete',
            objstore__pb2.DeleteRequest.SerializeToString,
            objstore__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/List',
            objstore__pb2.ListRequest.SerializeToString,
            objstore__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/Exists',
            objstore__pb2.ExistsRequest.SerializeToString,
            objstore__pb2.ExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/GetMetadata',
            objstore__pb2.GetMetadataRequest.SerializeToString,
            objstore__pb2.MetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/UpdateMetadata',
            objstore__pb2.UpdateMetadataRequest.SerializeToString,
            objstore__pb2.UpdateMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/Health',
            objstore__pb2.HealthRequest.SerializeToString,
            objstore__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Archive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/Archive',
            objstore__pb2.ArchiveRequest.SerializeToString,
            objstore__pb2.ArchiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/AddPolicy',
            objstore__pb2.AddPolicyRequest.SerializeToString,
            objstore__pb2.AddPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/RemovePolicy',
            objstore__pb2.RemovePolicyRequest.SerializeToString,
            objstore__pb2.RemovePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/GetPolicies',
            objstore__pb2.GetPoliciesRequest.SerializeToString,
            objstore__pb2.GetPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/ApplyPolicies',
            objstore__pb2.ApplyPoliciesRequest.SerializeToString,
            objstore__pb2.ApplyPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddReplicationPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/AddReplicationPolicy',
            objstore__pb2.AddReplicationPolicyRequest.SerializeToString,
            objstore__pb2.AddReplicationPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveReplicationPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/RemoveReplicationPolicy',
            objstore__pb2.RemoveReplicationPolicyRequest.SerializeToString,
            objstore__pb2.RemoveReplicationPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplicationPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/GetReplicationPolicies',
            objstore__pb2.GetReplicationPoliciesRequest.SerializeToString,
            objstore__pb2.GetReplicationPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplicationPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/GetReplicationPolicy',
            objstore__pb2.GetReplicationPolicyRequest.SerializeToString,
            objstore__pb2.GetReplicationPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerReplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/TriggerReplication',
            objstore__pb2.TriggerReplicationRequest.SerializeToString,
            objstore__pb2.TriggerReplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplicationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objstore.v1.ObjectStore/GetReplicationStatus',
            objstore__pb2.GetReplicationStatusRequest.SerializeToString,
            objstore__pb2.GetReplicationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
