# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: objstore.proto for package 'objstore.v1'

require 'grpc'
require_relative 'objstore_pb'

module Objstore
  module V1
    module ObjectStore
      # ObjectStore service provides a unified interface for object storage operations.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'objstore.v1.ObjectStore'

        # Put stores an object in the backend.
        rpc :Put, ::Objstore::V1::PutRequest, ::Objstore::V1::PutResponse
        # Get retrieves an object from the backend with streaming support for large files.
        rpc :Get, ::Objstore::V1::GetRequest, stream(::Objstore::V1::GetResponse)
        # Delete removes an object from the backend.
        rpc :Delete, ::Objstore::V1::DeleteRequest, ::Objstore::V1::DeleteResponse
        # List returns a list of objects that match the given criteria.
        rpc :List, ::Objstore::V1::ListRequest, ::Objstore::V1::ListResponse
        # Exists checks if an object exists in the backend.
        rpc :Exists, ::Objstore::V1::ExistsRequest, ::Objstore::V1::ExistsResponse
        # GetMetadata retrieves only the metadata for an object without its content.
        rpc :GetMetadata, ::Objstore::V1::GetMetadataRequest, ::Objstore::V1::MetadataResponse
        # UpdateMetadata updates the metadata for an existing object.
        rpc :UpdateMetadata, ::Objstore::V1::UpdateMetadataRequest, ::Objstore::V1::UpdateMetadataResponse
        # Health check endpoint for service health monitoring.
        rpc :Health, ::Objstore::V1::HealthRequest, ::Objstore::V1::HealthResponse
        # Archive copies an object to an archival storage backend.
        rpc :Archive, ::Objstore::V1::ArchiveRequest, ::Objstore::V1::ArchiveResponse
        # AddPolicy adds a new lifecycle policy.
        rpc :AddPolicy, ::Objstore::V1::AddPolicyRequest, ::Objstore::V1::AddPolicyResponse
        # RemovePolicy removes an existing lifecycle policy.
        rpc :RemovePolicy, ::Objstore::V1::RemovePolicyRequest, ::Objstore::V1::RemovePolicyResponse
        # GetPolicies retrieves all lifecycle policies.
        rpc :GetPolicies, ::Objstore::V1::GetPoliciesRequest, ::Objstore::V1::GetPoliciesResponse
        # ApplyPolicies executes all lifecycle policies.
        rpc :ApplyPolicies, ::Objstore::V1::ApplyPoliciesRequest, ::Objstore::V1::ApplyPoliciesResponse
        # Replication methods
        #
        # AddReplicationPolicy adds a new replication policy.
        rpc :AddReplicationPolicy, ::Objstore::V1::AddReplicationPolicyRequest, ::Objstore::V1::AddReplicationPolicyResponse
        # RemoveReplicationPolicy removes an existing replication policy.
        rpc :RemoveReplicationPolicy, ::Objstore::V1::RemoveReplicationPolicyRequest, ::Objstore::V1::RemoveReplicationPolicyResponse
        # GetReplicationPolicies retrieves all replication policies.
        rpc :GetReplicationPolicies, ::Objstore::V1::GetReplicationPoliciesRequest, ::Objstore::V1::GetReplicationPoliciesResponse
        # GetReplicationPolicy retrieves a specific replication policy.
        rpc :GetReplicationPolicy, ::Objstore::V1::GetReplicationPolicyRequest, ::Objstore::V1::GetReplicationPolicyResponse
        # TriggerReplication triggers synchronization for one or all policies.
        rpc :TriggerReplication, ::Objstore::V1::TriggerReplicationRequest, ::Objstore::V1::TriggerReplicationResponse
        # GetReplicationStatus retrieves status and metrics for a specific replication policy.
        rpc :GetReplicationStatus, ::Objstore::V1::GetReplicationStatusRequest, ::Objstore::V1::GetReplicationStatusResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
